version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8888:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./client:/usr/share/nginx/html
      - ./backend/static:/usr/share/nginx/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/var:/var/lib/letsencrypt
#      - ./client:/usr/share/nginx/html
#    depends_on:
#      - web
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /usr/share/nginx/html -d urlscan.kaduu.io --email koshchuk.r@gmail.com --agree-tos --no-eff-email -n; sleep 12h & wait $${!}; done;'"